seed = 0
batch_size = 1024
patience = 16
n_epochs = inf

[data]
seed = 0
cache = false
path = "/data/Blob_EastUS/xumeng/data/tabular/tabr/resample/covtype"
num_policy = "quantile"
cat_policy = "ordinal"
y_policy = "__null__"

[optimizer]
type = "AdamW"
lr = 1e-04
weight_decay = 1e-05

[model]
d_token = 192
n_blocks = 3
attention_dropout = 0.2
ffn_d_hidden_factor = 1.33333
ffn_dropout = 0.1
residual_dropout = 0.0
