seed = 0

[data]
seed = 0
num_policy = "__null__"
cache = false
path = "/data/Blob_WestJP/xumeng/data/tabular/tabr/resample/higgs-small"
cat_policy = "__null__"
y_policy = "__null__"

[model]
n_estimators = 4000
n_jobs = 4

[fit]
early_stopping_rounds = 3999
verbose = true
