seed = 0

[data]
seed = 0
num_policy = "__null__"
cache = true
path = "/data/Blob_EastUS/xumeng/data/tabular/tabr/resample/covtype"
cat_policy = "one-hot"
y_policy = "__null__"

[model]
n_estimators = 4000
n_jobs = 4

[fit]
early_stopping_rounds = 200
verbose = true
