seed = 1

[data]
seed = 0
num_policy = "__null__"
cache = false
path = "/data/Blob_WestJP/xumeng/data/tabular/tabr/resample/weather-small"
cat_policy = "__null__"
y_policy = "standard"

[model]
n_estimators = 4000
n_jobs = 4

[fit]
early_stopping_rounds = 3999
verbose = true
