seed = 0

[data]
seed = 0
num_policy = "__null__"
cat_policy = "__null__"
cache = false
path = "/data/Blob_EastUS/xumeng/data/tabular/tabr/resample/covtype"
y_policy = "__null__"

[model]
iterations = 4000
early_stopping_rounds = 3999
thread_count = 4
task_type = "CPU"
od_pval = 0.001

[fit]
logging_level = "Verbose"
